### ISSUE TITLE
[Reccomendation] Document usage as a drop-in replacement without config changes

### ISSUE THREAD

**Issue by JustusFluegel** [ryansonshine/cz-cli#5]
Hey there, just noticed this package after I found the issue on the original repo, thx for the work.

I have a small recommendation for you:
Using npm you can install another version of a package with a different name as follows:
````bash
npm install package@npm:other-package
````
This works since npm version 6.9.0.

so you could install this package with the name commitizen like that:

````bash
npm install commitizen@npm:@ryansonshine/commitizen
````

this would then work without changing the config, same for cz-conventional-changelog.

**Comment by jspr-vc** [comment]
@ryansonshine this might be a good approach for this fork, this way the code didn't have to be modified

**Comment by ryansonshine** [comment]
Hey, thanks for the suggestion!

I initially went the route with an aliased package, but one of my enterprise clients' security scanning tools couldn't parse the aliased package version, so I ultimately went the rename route.

Given that I maintain this package for my enterprise clients, I have to meet their needs first, so, unfortunately, I won't be able to make this change.
